# Builder
FROM node:22-alpine AS builder

WORKDIR /app

RUN npm install dotenv
RUN npm install -g prisma

# Copy the rest of the files
COPY site/prisma.config.ts ./
COPY site/prisma ./prisma

CMD ["npx", "prisma", "migrate", "deploy"]
