// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { assert, assertDefined } from "./src/lib";
import "dotenv/config";
import { defineConfig } from "prisma/config";

const getPostgresUrl = (): string => {
  const POSTGRES_URL = process.env.POSTGRES_URL;
  assertDefined(
    POSTGRES_URL,
    "POSTGRES_URL is not defined in environment variables",
  );

  if (!POSTGRES_URL.includes("$")) {
    return POSTGRES_URL;
  }

  let updatedUrl = POSTGRES_URL;
  for (const [key, value] of Object.entries(process.env)) {
    if (value === undefined) {
      continue;
    }

    const placeholder = `$\{${key}\}`;
    if (updatedUrl.includes(placeholder)) {
      updatedUrl = updatedUrl.replace(placeholder, value);
    }
  }

  assert(
    !updatedUrl.includes("$"),
    "All placeholders in POSTGRES_URL were not replaced",
  );
  return updatedUrl;
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getPostgresUrl(),
  },
});
